version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    container_name: mykakeibo-db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5555:5432'

  mykakeibo-api:
    image: mykakeibo-api
    environment:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres